encyclopedia/urls.py
from django.urls import path

from . import views

app_name="wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:name>", views.title, name="title")
    ]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponse

from . import util

class SearchQuery(forms.Form):
    q=forms.CharField(help_text="Search Encyclopedia")

def index(request):
    if request.method== "POST":
        query=request.POST.get("q")
        entries=[]
        aww=util.list_entries
        for stri in aww:
            if (stri.lowercase()).find(query.lowercase())!=-1:
                entries.append(stri)
        return render(request, "encyclopedia/index.html", {
            "entries": entries,
            "title": f"Search Result: {query.capitalize()}",
            "form": SearchQuery(request.POST)
        })
    else:
        return render(request, "encyclopedia/index.html", {
            "entries": util.list_entries(),
            "title": "All Pages",
            "form": SearchQuery()
    })

def title(request, name):
    return render(request, "encyclopedia/title.html", {
        "name": name,
        "body": util.get_entry(name),
        "form": SearchQuery()
    })


    
    

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>{{ title }}</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'wiki:title' name=entry %}" >  {{ entry }}  </a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:index' %}" method="POST">
                    {% csrf_token %}
                    <input class="searchs" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    Create New Page
                </div>
                <div>
                    Random Page
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/title.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ name }}
{% endblock %}

{% block body %}
    <h1>{{ name }}</h1>
    {% if body == None %}
    Requested Page was NOT Found
    {% else %}
    {{ body }}
    {% endif %}
{% endblock %}